version: '3.7'

services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/app/static
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
