version: '3.9'

services:
  
  django_gunicorn:
    volumes:
      - static:/static
      - .:/app:ro
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
      - 8000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - "*.pyc"
            - "__pycache__"
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      django_gunicorn:
        condition: service_healthy
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    env_file:
      - .env

volumes:
  static:
  postgres_data:
