version: '3.9'

services:
  
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    # expose:
    #   - 8000
    # networks:
    #   - app_network
    ports:
      - "90:5000"
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:8000"
    depends_on:
      - django_gunicorn
    # networks:
    #   - app_network
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    env_file:
      - .env
    # networks:
    #   - app_network

# networks:
#   app_network

volumes:
  static:
  postgres_data:
