# Generated by Django 5.0.6 on 2024-06-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobposts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='author name')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposts.jobpost')),
            ],
        ),
    ]
