# Generated by Django 5.0.6 on 2024-06-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_num', models.CharField(max_length=255, verbose_name='author contact number')),
                ('title', models.CharField(max_length=255, verbose_name='post title')),
                ('description', models.CharField(max_length=255, verbose_name='post description')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date posted')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
